// src/app/component/app.svelte
<script>
  import Header from "./header.svelte";
  import Preview from "./preview.svelte";
  import ToolPanel from "./tool-panel.svelte";
  import FixModal from "./fix-modal.svelte";
  import data from "../data/parts.js";
  import { TITLE_TEXT } from "../data/const.js";
  import {
    getDefaultSettings,
    generateFixImgSrcBySettings,
  } from "../domain/core.js";
  export let appType;

  const scheme = data[appType];
  const title = TITLE_TEXT[appType];

  let showFixModal = false;
  const toggleFixModal = () => (showFixModal = !showFixModal);

  const settings = getDefaultSettings(appType);
  const onUpdateSettings = ({ detail }) => {
    const { value, target } = detail;
    settings[target] = value;
  };

  let fixImgSrc = "";
  $: {
    generateFixImgSrcBySettings(scheme, settings)
      .then((src) => (fixImgSrc = src))
      .catch(console.error)
  }
</script>

<svelte:head>
  <title>{title}スーパーイカメーカー</title>
</svelte:head>

<Header on:show:fixModal={toggleFixModal} />
<Preview {fixImgSrc} />
<ToolPanel
  settings={settings}
  {scheme}
  {appType}
  on:update:settings={onUpdateSettings}
/>
<FixModal isShow={showFixModal} on:hide:fixModal={toggleFixModal}>
  <Preview {fixImgSrc} />
</FixModal>

// src/script/components/app.jsx
'use strict';
import * as React from 'react'; // eslint-disable-line no-unused-vars
import {Flux} from 'flumpt';
import objectAssign from 'object-assign';
import Header from './header.jsx';
import Preview from './preview.jsx';
import ToolPanel from './tool-panel.jsx';
import FixModal from './fix-modal.jsx';

export default class extends Flux {
  subscribe() {
    this.on('set:color', ({target, colorId}) => {
      this.update((state) => {
        state.settings[`${target}Color`] = colorId;
        return objectAssign({}, state);
      });
    });

    this.on('set:type', ({target, typeId}) => {
      this.update((state) => {
        state.settings[`${target}Type`] = typeId;
        return objectAssign({}, state);
      });
    });

    this.on('show:fixModal', () => {
      this.update((state) => {
        state.showFixModal = true;
        return objectAssign({}, state);
      });
    });

    this.on('hide:fixModal', () => {
      this.update((state) => {
        state.showFixModal = false;
        return objectAssign({}, state);
      });
    });
  }

  render(state) {
    return (
      <div>
        <Header />
        <Preview settings={state.settings} />
        <ToolPanel {...state} />
        <FixModal isShow={state.showFixModal} />
      </div>
    );
  }
};
